import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const csvPath = path.join(__dirname, '../src/lib/tall_ships_itinerary.csv')
const outPath = path.join(__dirname, '../src/lib/ships-data.ts')

const DATE_COLS = ['Jul 5', 'Jul 6', 'Jul 7']

function parseNum(s) {
  if (!s || s.trim() === '') return null
  const n = parseFloat(s.replace(/,/g, ''))
  return isNaN(n) ? null : n
}

function neighborhood(city) {
  if (!city) return null
  return city
}

const raw = fs.readFileSync(csvPath, 'utf-8').replace(/^﻿/, '')
const lines = raw.trim().split('\n')

const ships = lines.slice(1).map(line => {
  const cols = []
  let cur = '', inQuote = false
  for (const ch of line) {
    if (ch === '"') { inQuote = !inQuote }
    else if (ch === ',' && !inQuote) { cols.push(cur.trim()); cur = '' }
    else { cur += ch }
  }
  cols.push(cur.trim())

  const [country, name, sqft, length, capacity, pier, city, d5, d6, d7] = cols

  const dates = []
  if (d5 === '1') dates.push(DATE_COLS[0])
  if (d6 === '1') dates.push(DATE_COLS[1])
  if (d7 === '1') dates.push(DATE_COLS[2])

  const nb = neighborhood(city)
  const location = pier && city ? `${city}: ${pier}` : null

  return {
    country: country || '',
    name: name || '',
    sqftSail: parseNum(sqft),
    lengthFt: parseNum(length),
    capacity: capacity || null,
    location,
    pier: pier || null,
    neighborhood: nb,
    dates,
  }
})

const out = `// Auto-generated by scripts/parse-ships.mjs — do not edit manually
import type { Ship } from './ships'

export const SHIPS_DATA: Ship[] = ${JSON.stringify(ships, null, 2)}
`

fs.writeFileSync(outPath, out)
console.log(`✓ Wrote ${ships.length} ships to src/lib/ships-data.ts`)
